#!/usr/bin/env python3
"""
Generate Nancy Pelosi portfolio tracker report
"""
import json
import sys
from datetime import datetime, date
from pathlib import Path

def calculate_days_to_expiry(expiry_date_str):
    """Calculate days to option expiry"""
    try:
        expiry = datetime.strptime(expiry_date_str, '%Y-%m-%d').date()
        today = date.today()
        days = (expiry - today).days
        return max(0, days)
    except:
        return 0

def calculate_option_intrinsic_value(current_price, strike, option_type='call'):
    """Calculate option intrinsic value"""
    if option_type == 'call':
        return max(0, current_price - strike)
    else:
        return max(0, strike - current_price)

def calculate_moneyness(current_price, strike, option_type='call'):
    """Calculate how much ITM/OTM as percentage"""
    if option_type == 'call':
        if current_price > strike:
            return round((current_price - strike) / strike * 100, 1)
        return round((current_price - strike) / strike * 100, 1)
    return 0

def format_position(position):
    """Format a single position for display"""
    ticker = position['ticker']
    pos_type = position['type']
    current_price = position.get('current_price', 0)
    
    lines = []
    lines.append(f"📊 {ticker}")
    
    if pos_type == 'call_option':
        strike = position['strike']
        expiry = position['expiry']
        intrinsic = calculate_option_intrinsic_value(current_price, strike)
        moneyness = calculate_moneyness(current_price, strike)
        dte = calculate_days_to_expiry(expiry)
        
        lines.append(f"   Type: Call Option ${strike} Strike")
        lines.append(f"   Expiry: {expiry} ({dte} days)")
        lines.append(f"   Current: ${current_price}")
        lines.append(f"   Intrinsic Value: ${intrinsic:.2f}/share")
        lines.append(f"   Moneyness: {moneyness}% {'ITM' if moneyness > 0 else 'OTM'}")
        
    elif pos_type == 'stock':
        quantity = position.get('quantity', 'unknown')
        value_range = position.get('value_range', '')
        lines.append(f"   Type: Stock")
        lines.append(f"   Current: ${current_price}")
        if quantity != 'unknown':
            position_value = current_price * quantity
            lines.append(f"   Quantity: {quantity:,} shares")
            lines.append(f"   Est. Value: ${position_value:,.0f}")
        if value_range:
            lines.append(f"   Disclosed Range: {value_range}")
    
    # Check alerts
    if 'alerts' in position:
        upside = position['alerts'].get('upside_target')
        support = position['alerts'].get('support_level')
        
        if upside and current_price >= upside:
            lines.append(f"   🚨 ALERT: Above upside target ${upside}!")
        elif support and current_price <= support:
            lines.append(f"   🚨 ALERT: Below support ${support}!")
        else:
            lines.append(f"   🟢 Status: Normal range")
    
    if 'notes' in position:
        lines.append(f"   💡 {position['notes']}")
    
    return '\n'.join(lines)

def generate_report(config_path, template_path=None):
    """Generate full portfolio report"""
    with open(config_path, 'r') as f:
        config = json.load(f)
    
    lines = []
    lines.append("📊 Nancy Pelosi Portfolio Tracker Report")
    lines.append("=" * 50)
    lines.append(f"📅 Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"📈 Last Data Update: {config.get('last_updated', 'Unknown')}")
    lines.append("")
    
    # Active positions
    active_positions = [p for p in config['positions'] if p['status'] == 'active']
    lines.append(f"💼 Active Positions: {len(active_positions)}")
    lines.append("")
    
    for position in active_positions:
        lines.append(format_position(position))
        lines.append("")
    
    # Check for triggered alerts
    alerts_triggered = []
    for position in active_positions:
        if 'alerts' not in position or 'current_price' not in position:
            continue
        
        current = position['current_price']
        upside = position['alerts'].get('upside_target')
        support = position['alerts'].get('support_level')
        
        if upside and current >= upside:
            alerts_triggered.append(f"{position['ticker']}: Above ${upside}")
        elif support and current <= support:
            alerts_triggered.append(f"{position['ticker']}: Below ${support}")
    
    lines.append("🚨 Alert Summary")
    lines.append("-" * 30)
    if alerts_triggered:
        for alert in alerts_triggered:
            lines.append(f"  ⚠️ {alert}")
    else:
        lines.append("  🟢 No alerts triggered")
    
    lines.append("")
    lines.append("=" * 50)
    lines.append("🤖 Generated by Nancy Pelosi Tracker")
    
    return '\n'.join(lines)

def generate_markdown_report(config_path):
    """Generate markdown formatted report for Telegram"""
    with open(config_path, 'r') as f:
        config = json.load(f)
    
    lines = []
    lines.append("📊 **Nancy Pelosi Portfolio Tracker**")
    lines.append(f"📅 *{datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    lines.append("")
    
    active_positions = [p for p in config['positions'] if p['status'] == 'active']
    
    for i, position in enumerate(active_positions, 1):
        ticker = position['ticker']
        current_price = position.get('current_price', 0)
        
        lines.append(f"{i}. **{ticker}**")
        
        if position['type'] == 'call_option':
            strike = position['strike']
            expiry = position['expiry']
            intrinsic = calculate_option_intrinsic_value(current_price, strike)
            dte = calculate_days_to_expiry(expiry)
            
            lines.append(f"   ├─ Call ${strike} | Exp: {expiry} ({dte}d)")
            lines.append(f"   ├─ Price: ${current_price} | Intrinsic: ${intrinsic:.2f}")
        else:
            lines.append(f"   ├─ Stock | Price: ${current_price}")
        
        if 'alerts' in position:
            upside = position['alerts'].get('upside_target')
            support = position['alerts'].get('support_level')
            lines.append(f"   └─ Alerts: ↑${upside} ↓${support}")
        
        lines.append("")
    
    return '\n'.join(lines)

if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate Pelosi tracker report')
    parser.add_argument('--config', default='config/positions.json', help='Config file path')
    parser.add_argument('--format', choices=['text', 'markdown'], default='text', help='Output format')
    parser.add_argument('--output', help='Output file (default: stdout)')
    
    args = parser.parse_args()
    
    if args.format == 'markdown':
        report = generate_markdown_report(args.config)
    else:
        report = generate_report(args.config)
    
    if args.output:
        with open(args.output, 'w') as f:
            f.write(report)
        print(f"Report saved to {args.output}")
    else:
        print(report)
